### ISSUE TITLE
Configuration on Windows and Linux when built as Slicer extension

### ISSUE THREAD

**Issue by hina-shah** [NIRALUser/ShapePopulationViewer#18]
[Slicer dashboard](http://slicer.cdash.org/buildSummary.php?buildid=1006940) indicates that Shape population viewer configuration/build is failing in [src/CMakeLists.txt](https://github.com/NIRALUser/ShapePopulationViewer/blob/master/src/CMakeLists.txt#L115) on Linux and Windows builds.

**Comment by hina-shah** [comment]
This was resolved in #19

**Comment by jcfr** [comment]
@ninatubau @juanprietob  Since this was addressed, could you close this issue ?
