### ISSUE TITLE
Remove release branch

### ISSUE THREAD

**Issue by jcfr** [NIRALUser/ShapePopulationViewer#33]
@juanprietob Having the `release` branch ends up being confusing. <s>Instead, I suggest that tagged like `YYYY-MM-DD` are created when the code is stable.</s>

Cc: @juanprietob

**Comment by juanprietob** [comment]
The 'release' branch is to not update the .s4ext files every time there is a new update. 
This file will point always to the latest version.

**Comment by jcfr** [comment]
> The 'release' branch is to not update the .s4ext files every time there is a new update.
> This file will point always to the latest version.

The problem is that after changes a merged to `master`, there is no process to decide if the `release` should be updated. It was last updated in 2014. I suggest to simply remove it. The description file already reference the master branch (see https://github.com/Slicer/ExtensionsIndex/pull/1595)

**Comment by juanprietob** [comment]
The release branch contains the latest release. 
It is updated when the release is ready. 

Are all .s4ext pointing to the master branch now? 
If it is the case then, I'll remove the release branch. I have release branch for all the NIRAL extensions.

**Comment by jcfr** [comment]
> The release branch contains the latest release.
> It is updated when the release is ready.

You could:
* use the `release` branch of ShapePopulationViewer in the extension index associated with the last stable release of Slicer 
* and use `master` branch of ShapePopulationViewer in the index user to build the nightly extension

That way, you ensure user can experiment with the latest version of the tools while keeping the version associated with Slicer 4.10 stable.

> Are all .s4ext pointing to the master branch now?

Some of them, the requirements is that maintainer of extension either keep their extension backward compatible with the last release or create a `master-4.10` branch in their project.

**Comment by juanprietob** [comment]
> * use the `release` branch of ShapePopulationViewer in the extension index associated with the last stable release of Slicer

This is the case already then, right? 



> * and use `master` branch of ShapePopulationViewer in the index user to build the nightly extension

Is there another ExtensionIndex? What do you mean by the index user? Is it the index you checkout and build yourself? 



> Some of them, the requirements is that maintainer of extension either keep their extension backward compatible with the last release or create a `master-4.10` branch in their project.

Does this mean all extensions should have a tag `master-4.10`

**Comment by jcfr** [comment]
> This is the case already then, right?

It was but it never got updated. Hence my recent change  (see Slicer/ExtensionsIndex#1595) and this discussion.

> Is there another ExtensionIndex? What do you mean by the index user? Is it the index you checkout and build yourself?

This was a typo. ` index user` -> ` index used`


> Does this mean all extensions should have a tag master-4.10

If you want to continue development of the extension associated with the stable release, and don't want to explicitly update the SHA. I would say, yes.
