### ISSUE TITLE
Create reusable widget to streamline integration in Slicer

### ISSUE THREAD

**Issue by jcfr** [NIRALUser/ShapePopulationViewer#35]

**Comment by bpaniagua** [comment]
@jcfr Great idea.

We should keep the stand-alone CLI as a build option, the program is still used as stand-aloe commandline application by much of our userbase.

**Comment by bpaniagua** [comment]
Hi @jcfr 
wrt https://github.com/NIRALUser/ShapePopulationViewer/pull/36

are we still keeping the stand-alone CLI?

**Comment by jcfr** [comment]
> are we still keeping the stand-alone CLI?
Yes. 

When built as a standalone project, the CLI will be built.

When build against Slicer, the default will be to build the "loadable module" with the option of disabling that and still building the CLI

**Comment by bpaniagua** [comment]
@jcfr 

@juanprietob has reported the stand alone CLI does not build. I am in the process of making a local build and verifying.

**Comment by bpaniagua** [comment]
@juanprietob are you guys ok with deprecating qt4 for this application? we will still provide support for stand-alone vs Slicer extension.

**Comment by juanprietob** [comment]
Yes, I'm ok with only qt5 support.

**Comment by jcfr** [comment]
Great. We will then simplify the extension and fix the build as a standalone project against Qt5.
