### ISSUE TITLE
Shape Population Viewer on Linux will not display color pick dialog

### ISSUE THREAD

**Issue by bpaniagua** [NIRALUser/ShapePopulationViewer#43]
When using SPV on Linux as an integrated widget, the color pick dialog for the color bar will not show up when double clicking the circle within the colorbar. 

cc: @jcfr

**Comment by bpaniagua** [comment]
Update, it does not work for MacOS either. 
It does work for Slicer, not for SlicerSALT

**Comment by jcfr** [comment]
"Problem" has been identified, a fix is being implemented.
In a nutshell, in the standalone SPV, the GPL version of the Qt widget is used, in the one integrated, we rely on VTK chart and the "double click on point" event wasn't wired.

**Comment by jcfr** [comment]
After enabling the widget on top of the gradient, here is how it looks:

![image](https://user-images.githubusercontent.com/219043/62980000-56a70600-bdf3-11e9-8dd1-af2ffd92e6fb.png)

The next step is to make sure the change are propagated to the loaded models without having to click on "Reset range" button

**Comment by bpaniagua** [comment]
Is this ready for testing? If so what version?

**Comment by jcfr** [comment]
Change integrated in ShapePopulationViewer and ExtensionIndex updated
