### ISSUE TITLE
Move test data away from midas server

### ISSUE THREAD

**Issue by allemangD** [NIRALUser/ShapePopulationViewer#57]
Testing fails since data can't be provided by the midas server outside the Kitware network. See #56.

**Comment by jcfr** [comment]
Data have been uploaded to [Slicer/SlicerTestingData](https://github.com/Slicer/SlicerTestingData) and external data url template updated in [e2426bf](https://github.com/NIRALUser/ShapePopulationViewer/pull/60/commits/e2426bfc3788788773f411a924b22acc6e8698d9)
