### ISSUE TITLE
Release 1.4.0 on NITRC

### ISSUE THREAD

**Issue by agirault** [NIRALUser/ShapePopulationViewer#8]
Do you guys plan to upload the newest releases on NITRC (1.4.0)? The last downloadable version is still 1.3.2 (2 years old), so no update since @laurapascal worked on it: https://www.nitrc.org/projects/shapepopviewer/

**Comment by juanprietob** [comment]
We are still debating if we are going to maintain the NITRC version since ShapePopulationViewer is accessible through Slicer. 
@laurapascal what do you think? Should we create executables for linux/max/windows?

**Comment by agirault** [comment]
Some functionalities are removed in Slicer extension correct? Like PDF export.

The only users I know use SPV directly, opening Slicer before is often slow and only keeps an instance of Slicer open which most of the time is not needed.

Just my 2c.

**Comment by laurapascal** [comment]
Considering what you said @agirault , we will work on it. 
Thank for your feedback.

**Comment by jcfr** [comment]
@ninatubau @juanprietob  Should this be closed ?
